$color = rgba(1, 2, 6, 1)
$inner_color = rgba(1, 2, 6, 0.66)
$outer_color = rgba(135, 166, 245, 1)
$font_color = rgba(233, 247, 244, 1)
$placeholder_color = rgba(233, 247, 244, 0.7)
$check_color = rgba(106, 230, 255, 1)
