background            #010206
foreground            #E9F7F4

# black
color0  #010206
color8  #5d5f65

# red
color1  #8b8cc9
color9  #9f9feb

# green
color2  #62d0f0
color10 #4debff

# yellow
color3  #74ffff
color11 #36ffff

# blue
color4  #4f80b7
color12 #5896d9

# magenta
color5  #87a6f5
color13 #94baff

#cyan
color6  #6ae6ff
color14 #5cffff

#white
color7  #E9F7F4
color15 #edf6ff


